In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')
import torch
torch.__version__
!pip install simpletransformers
!pip install --upgrade simpletransformers

In [2]:
from simpletransformers.classification import ClassificationModel, ClassificationArgs
import pandas as pd
import logging
from sklearn.metrics import f1_score, accuracy_score,classification_report

import wandb

logging.basicConfig(level=logging.INFO)
transformers_logger = logging.getLogger("transformers")
transformers_logger.setLevel(logging.WARNING)

train_df = pd.read_csv('/content/gdrive/MyDrive/fenlei/train_df1.csv')
train_df.columns = ["labels","text"]

eval_df = pd.read_csv('/content/gdrive/MyDrive/fenlei/eval_df1.csv')
eval_df.columns = ["labels","text"]

# dev_df = pd.read_csv('/content/gdrive/MyDrive/fenlei/dev_df.csv')
# dev_df.columns = ["labels","text"]

In [ ]:
train_data = [
    ["科学规划", 1],
    ["提高技术附加值和品牌附加值", 2],
    ["提升品牌营销层次", 3],
    ["分清组织机构责任", 4],
    ["增强品牌保护", 5],
]
train_df = pd.DataFrame(train_data)
train_df.columns = ["text", "labels"]

# Preparing eval data
eval_data = [
    ["品牌规划", 1],
    ["采用新技术", 2],
    ["加大营销力度", 3],
    ["规范组织机构", 2],
    ["制定保护细则", 3],
]
eval_df = pd.DataFrame(eval_data)
eval_df.columns = ["text", "labels"]

In [9]:
train_df

labels                               text
0         1                      “走特色化路、打差异化牌”
1         1   把品牌建设作为参与全球农业竞争的国家战略比如科学规划品牌发展战略
2         1   把品牌建设作为参与全球农业竞争的国家战略比如科学规划品牌发展战略
3         1              把握农产品区域公用品牌建设的核心与关键所在
4         1              把握农产品区域公用品牌建设的核心与关键所在
..      ...                                ...
608       5                   强化对江津花椒证明商标的使用管理
609       5                召开江津花椒地理标志商标使用单位座谈会
610       5                出台一江津彩农产品区域公用品牌管理办法
611       5                           培育富硒产业品牌
612       5  加强对江永香柚地理标志证明商标和农产品地理标志产品的保护和使用管理

[613 rows x 2 columns]

In [3]:
model_args = ClassificationArgs()
model_args.num_train_epochs=20
model_args.learning_rate = 1e-4
model_args.labels_list = [1, 2,3, 4,5]

model = ClassificationModel(
    'bert',
    'bert-base-chinese',
    num_labels=5,
    args=model_args
) 

Some weights of the model checkpoint at bert-base-chinese were not used when initializing BertForSequenceClassification: ['cls.predictions.decoder.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.weight']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at

In [4]:
model.train_model(train_df)

  0%|          | 0/360 [00:00<?, ?it/s]

Epoch:   0%|          | 0/20 [00:00<?, ?it/s]

Running Epoch 0 of 20:   0%|          | 0/45 [00:00<?, ?it/s]

Running Epoch 1 of 20:   0%|          | 0/45 [00:00<?, ?it/s]

Running Epoch 2 of 20:   0%|          | 0/45 [00:00<?, ?it/s]

Running Epoch 3 of 20:   0%|          | 0/45 [00:00<?, ?it/s]

Running Epoch 4 of 20:   0%|          | 0/45 [00:00<?, ?it/s]

Running Epoch 5 of 20:   0%|          | 0/45 [00:00<?, ?it/s]

Running Epoch 6 of 20:   0%|          | 0/45 [00:00<?, ?it/s]

Running Epoch 7 of 20:   0%|          | 0/45 [00:00<?, ?it/s]

Running Epoch 8 of 20:   0%|          | 0/45 [00:00<?, ?it/s]

Running Epoch 9 of 20:   0%|          | 0/45 [00:00<?, ?it/s]

Running Epoch 10 of 20:   0%|          | 0/45 [00:00<?, ?it/s]

Running Epoch 11 of 20:   0%|          | 0/45 [00:00<?, ?it/s]

Running Epoch 12 of 20:   0%|          | 0/45 [00:00<?, ?it/s]

Running Epoch 13 of 20:   0%|          | 0/45 [00:00<?, ?it/s]

Running Epoch 14 of 20:   0%|          | 0/45 [00:00<?, ?it/s]

Running Epoch 15 of 20:   0%|          | 0/45 [00:00<?, ?it/s]

Running Epoch 16 of 20:   0%|          | 0/45 [00:00<?, ?it/s]

Running Epoch 17 of 20:   0%|          | 0/45 [00:00<?, ?it/s]

Running Epoch 18 of 20:   0%|          | 0/45 [00:00<?, ?it/s]

Running Epoch 19 of 20:   0%|          | 0/45 [00:00<?, ?it/s]

(900, 0.19165810278720327)

In [5]:
from sklearn.metrics import precision_score,recall_score

def f1_multiclass(labels, preds):
      return precision_score(labels,preds,average='macro'),recall_score(labels,preds,average='macro'),f1_score(labels, preds, average='macro')
result, model_outputs, wrong_predictions = model.eval_model(eval_df, f1=f1_multiclass, acc=accuracy_score)
print(result)

  0%|          | 0/90 [00:00<?, ?it/s]

Running Evaluation:   0%|          | 0/12 [00:00<?, ?it/s]

{'mcc': 0.9025364259450579, 'f1': (0.9348654244306417, 0.9099999999999999, 0.9186638272747476), 'acc': 0.9222222222222223, 'eval_loss': 0.5167393684387207}


In [15]:
predictions, raw_outputs = model.predict(["压实各方监管责任","提升质量安全保障","优化种植结构、推广农业新科技","推进农产品地理标志商标注册使用和保护工作","建立本地农产品在浙江直销网络"])
print(predictions, raw_outputs)

  0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

[5, 2, 2, 4, 3] [[-1.85058594 -0.75976562 -1.71484375 -1.375       4.57421875]
 [-1.44140625  5.30078125 -1.29199219 -1.99707031 -1.421875  ]
 [-0.32226562  4.42578125 -0.07067871 -2.68945312 -1.96191406]
 [-1.25585938 -1.45117188 -1.11816406  5.53125    -0.60888672]
 [-1.08300781 -0.46484375  4.08203125 -2.33203125 -0.73046875]]


In [6]:
import csv
with open('/content/gdrive/MyDrive/fenlei/data_shandong.csv','r',encoding='utf-8') as csvfile:
    reader = csv.reader(csvfile)
    print(type(reader))
    column = [row[0] for row in reader]

<class '_csv.reader'>


In [7]:
column

['\ufefftext',
 '挖掘培育独具新区特色的地标',
 '结合新区特色农产品、水产品等生产经营状况和商标管理使用情况',
 '加强商标注册行政指导',
 '积极培育、申报和保护地理标志证明商标',
 '与各部门和镇街沟通协调',
 '落实新区品牌创建推广战略',
 '促进了特色行业发展和群众增产增收',
 '利用与保存自然资源、人文资源和地理遗产',
 '组织王台酥梨、杨家山里樱桃、大场水果萝卜、阡上阡里虾等申请注册地理标志证明商标',
 '保护了优质特色产品',
 '加强区域品牌整合',
 '采取多种措施',
 '召开2021年会暨地理标志助推乡村振兴发展推进会',
 '加大了科技投入',
 '撒施有机肥',
 '采用高频振频杀虫灯和粘虫板杀灭害虫',
 '按照有机蔬菜种植要求',
 '喷洒牛奶用作叶面肥',
 '科学规划',
 '强化特色产业区域化布局和连片种植',
 '提高产品质量和效益',
 '加快特色产业基地建设',
 '加大对章丘鲍芹等特色农业品的打造力度',
 '加快扶持',
 '建立鲍芹绿色安全种植基地',
 '采用土地流转方式',
 '按照有机蔬菜标准要求',
 '形成了生产、包装、检测、配送一条龙的为农服务体系',
 '走进了上海世博会',
 '育良种',
 '通过了中韩共建国际食品安全示范区验收',
 '发展“三品一标”农产品449个',
 '实现了“源头无隐患、投入无违禁、管理无盲区、入市无障碍”',
 '加大农产品质量安全监管力度',
 '坚持一个标准统筹国内国际“两个市场”',
 '通过源头控制、过程监管、产地准出和市场准入',
 '创建为全国首个国家级农业综合标准化优秀示范市',
 '通过有机、绿色或无公害认证',
 '培强做大农产品产业集群',
 '注册“安丘农耕”农产品区域公共品牌',
 '纳入欧盟地理标志产品保护范围',
 '通过欧盟GAP和日本JAS有机食品认证',
 '通过HACCP、英国BRC、德国IFS等国际认证',
 '开展了2020安丘“十大新闻”评选活动',
 '建成国内首个县级',
 '投票选出您心目中的2020年度安丘“十大新闻”您心目中的2020年度安丘“十大新闻”动动您的手指，快来投票吧动动您的手指，快来投票吧投票日期：2021.1.1-2021.1.7投票日期：2021.1.1-2021.1.7

In [8]:
classi=[]
a=0
predictions= model.predict(column)
print(predictions)
# predictions[0]
# list = predictions[0].tolist()


  0%|          | 0/5745 [00:00<?, ?it/s]

  0%|          | 0/719 [00:00<?, ?it/s]

([2, 1, 5, 1, 4, 5, 1, 1, 2, 1, 4, 1, 5, 1, 2, 3, 2, 1, 3, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 2, 1, 2, 1, 5, 2, 1, 2, 1, 2, 1, 1, 4, 2, 2, 3, 1, 3, 2, 1, 1, 1, 1, 5, 2, 5, 2, 1, 2, 1, 2, 1, 1, 3, 2, 1, 1, 1, 1, 1, 2, 2, 2, 2, 5, 3, 2, 1, 2, 2, 1, 2, 5, 2, 5, 2, 2, 5, 2, 1, 2, 5, 1, 1, 1, 1, 5, 2, 3, 2, 1, 2, 1, 3, 3, 1, 2, 2, 2, 2, 2, 2, 1, 5, 2, 1, 1, 2, 3, 2, 1, 2, 1, 3, 1, 4, 2, 1, 1, 1, 2, 1, 2, 2, 2, 1, 4, 4, 1, 2, 2, 1, 1, 5, 1, 2, 1, 1, 1, 1, 1, 5, 5, 1, 1, 1, 2, 5, 1, 2, 2, 5, 2, 2, 2, 1, 2, 1, 5, 1, 2, 2, 1, 3, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 2, 3, 2, 2, 1, 2, 1, 5, 1, 1, 4, 5, 5, 3, 5, 2, 2, 2, 5, 5, 5, 2, 1, 1, 1, 3, 2, 1, 3, 2, 5, 1, 1, 1, 1, 3, 2, 2, 2, 2, 1, 1, 2, 3, 1, 1, 1, 5, 1, 1, 1, 1, 3, 2, 1, 1, 2, 1, 1, 5, 5, 1, 1, 5, 1, 5, 3, 4, 1, 2, 2, 2, 1, 2, 5, 2, 2, 3, 3, 1, 1, 3, 2, 1, 1, 1, 3, 2, 1, 2, 3, 2, 2, 5, 2, 1, 2, 2, 5, 2, 2, 5, 1, 2, 2, 3, 2, 4, 1, 1, 1, 2, 1, 4, 1, 1, 5, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 5, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [ ]:
len(column)
print(column[2])
print(list)

In [21]:
i=0
classi=[]
for c in column[1:]:
  i=i+1
  # print(i)
  # print(list[i])
  classi.append(
      {
          "label":list[i],"text":c
      }
  )

TypeError: ignored

In [ ]:
name=['label','text']
test=pd.DataFrame(columns=name,data=classi)#数据有三列，列名分别为one,two,three
print(test)
test.to_csv('dibiao.csv',encoding='utf-8',index = False)

       label                                               text
0          1      近日，“永昌胡萝卜”取得国家知识产权局地理标志证明商标注册证书，这是金昌市首件地理标...
1          0  中共武穴市委关于制定全市国民经济和社会发展第十四个五年规划和二〇三五年远景目标的建议...
2          1     6月8日，揭阳市埔田竹笋、吴厝淮山、普宁蕉柑、普宁青梅、惠来荔枝等5个地理标志产品的6...
3          1     广东省市场监督管理局关于开展地理标志产品专用标志使用核准改革试点的公告   2021年...
4          1     截止7月31日，受越南科技部知识产权局保护的国家地理标志产品有62种，国外地理标志产品...
...      ...                                                ...
17478      0  做最优生态环境，引最多优秀人才，聚最强高端产业。\n近年来，在“最强高端产业”上，泾河新城先...
17479      0  做最优生态环境，引最多优秀人才，聚最强高端产业。\n近年来在“最强高端产业”上，泾河新城先进...
17480      0  做最优生态环境，引最多优秀人才，聚最强高端产业。近年来，西咸新区泾河新城在“最强高端产业”上...
17481      0  做最优生态环境，引最多优秀人才，聚最强高端产业。近年来，在“最强高端产业”上，泾河新城先进制...
17482      0  做最优生态环境引最多优秀人才聚最强高端产业近年来在“最强高端产业”上泾河新城先进制造业加速布...

[17483 rows x 2 columns]


In [ ]:
# from simpletransformers.classification import ClassificationModel, ClassificationArgs
# import pandas as pd
# import logging
# from sklearn.metrics import f1_score, accuracy_score,classification_report

# import wandb
##多分类
def f1_multiclass(labels, preds):
      return f1_score(labels, preds, average='micro')

target_names = ["BACKGROUND", "OBJECTIVE","METHODS","RESULTS","CONCLUSIONS"]
def class_report(labels, preds):
  return classification_report(labels, preds, target_names=target_names,digits=4)

logging.basicConfig(level=logging.INFO)
transformers_logger = logging.getLogger("transformers")
transformers_logger.setLevel(logging.WARNING)

# Preparing train data
# train_data = [
#     ["Aragorn was the heir of Isildur", 1],
#     ["Frodo was the heir of Isildur", 0],
#     ["Pippin is stronger than Merry", 2],
# ]
# train_df = pd.DataFrame(train_data)
train_df = pd.read_csv('bert-train_new.csv')
train_df.columns = ["labels","text"]

# Preparing eval data
# eval_data = [
#     ["Aragorn was the heir of Elendil", 1],
#     ["Sam was the heir of Isildur", 0],
#     ["Merrry is stronger than Pippin", 2],
# ]
# eval_df = pd.DataFrame(eval_data)
eval_df = pd.read_csv('bert-test_new.csv')
eval_df.columns = ["labels","text"]


# Optional model configuration
# model_args = ClassificationArgs(num_train_epochs=1)
model_args = ClassificationArgs()
model_args.num_train_epochs=1
model_args.labels_list = ["BACKGROUND", "OBJECTIVE","METHODS","RESULTS","CONCLUSIONS"]

# model_args.reprocess_input_data = True
# model_args.overwrite_output_dir = True
# model_args.evaluate_during_training = True
# model_args.manual_seed = 4
# model_args.use_multiprocessing = True
# model_args.train_batch_size = 16
# model_args.eval_batch_size = 8

# model_args.wandb_project = "Scibert_rm"
# Create a ClassificationModel
model = ClassificationModel(
    'bert',
    'allenai/scibert_scivocab_uncased',
    num_labels=5,
    args=model_args
) 

# Train the model
# model.train_model(train_df,eval_df=eval_df)
model.train_model(train_df)

# Evaluate the model
# result, model_outputs, wrong_predictions = model.eval_model(eval_df)
# result, model_outputs, wrong_predictions = model.eval_model(eval_df, f1=f1_multiclass, acc=accuracy_score)
result, model_outputs, wrong_predictions = model.eval_model(eval_df, f1=f1_multiclass, acc=accuracy_score,report=class_report)
# Make predictions with the model
# predictions, raw_outputs = model.predict(["Sam was a Wizard"])

In [ ]:
predictions, raw_outputs = model.predict(["Pests have been greatly damaging the rice yield in Guangdong Province, China in recent year.", "Traditional pests warning models, based on the mathematical statistics, only considering the relation between weather and monitoring data factors, are limited in large place.","As a result, multi-factor spatial overlay model was construction to research the damage of Cnaphalocrocis medinalis in Guangdong Province.","The factors include the Cnaphalocrocis medinalis situation, crop condition, and external environment data. By using the GIS technology, the model can make the thematic maps of Cnaphalocrocis medinalis damage in different time.","The result can reproduce the spatio-temporal change of Cnaphalocrocis medinalis in Guangdong Province, as well as offer scientific support on prevention of rice pests."])
print(predictions, raw_outputs)

INFO:simpletransformers.classification.classification_utils: Converting to features started. Cache is not used.


  0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

['BACKGROUND', 'BACKGROUND', 'METHODS', 'CONCLUSIONS', 'CONCLUSIONS'] [[ 4.109375    0.13024902 -3.14453125 -2.109375   -0.66113281]
 [ 4.453125   -1.3359375  -3.54882812 -0.92578125  0.03411865]
 [ 0.82275391  0.83496094  1.47460938 -1.27832031 -1.78222656]
 [-0.60107422 -2.23242188 -1.96386719  0.60351562  4.4609375 ]
 [-0.80029297 -2.0546875  -2.37890625 -0.26025391  5.99609375]]


In [ ]:
predictions, raw_outputs = model.predict(["This paper attempts to address a recurring theme in agricultural resources and environmental economics - the low adoption rates of pro-environmental agricultural practices in many developing countries.","By improving the Norm-activation model, this paper incorporates external incentives and social norms into the framework and employs multivariate probit and ordered probit models to explore how environmental conscience, external incentives and social norms influence rice farmers' adoption behaviours and intensive use of pro-environmental agricultural practices.","The case study, involving 954 household-level data of rice farmers from rural Hubei province, China, reveals that the adoption rates of certain practices are very low, and that only 6.5% rice farmers adopt three or more pro-environmental agricultural practices.","Results show that straw returning and soil testing and fertilizer recommendation are complementaries, and that environmental conscience, external incentives and social norms all positively affect the adoption behaviours, while the adoption intensity is significantly influenced by awareness of consequences, perceived efficacy, external incentives and descriptive norm.","These findings underscore that policy interventions to improve rice farmers' environmental conscience, to provide well-designed external incentives and to activate social norms are needed to enhance the adoption of pro-environmental agricultural practices in developing countries."])
print(predictions, raw_outputs)

INFO:simpletransformers.classification.classification_utils: Converting to features started. Cache is not used.


  0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

['BACKGROUND', 'BACKGROUND', 'RESULTS', 'RESULTS', 'CONCLUSIONS'] [[ 4.28125    -0.14074707 -2.66210938 -0.66064453  0.54394531]
 [ 2.59375    -1.13574219 -1.12988281  1.74511719 -0.64404297]
 [-0.34619141 -2.9453125  -1.24414062  3.46679688  1.234375  ]
 [-2.34765625 -3.51171875 -1.91699219  4.421875    2.6015625 ]
 [-1.06054688 -2.234375   -2.59765625 -0.20251465  5.78515625]]


In [ ]:
predictions, raw_outputs = model.predict(["Rice leaf folder, Cnaphalocrocis medinalis(Guenee), has become a major pest throughout the rice cultivating areas of China and caused severe damage to rice production.","Cnaphalocrocis medinalis granulovirus (CnmeGV), a naturally occurring baculovirus, is revealed as a potential microbial agent for the pest control.","Field applications of CnmeGV were conducted against rice leaffolder larvae in rice paddies."," CnmeGV infected the larvae not only in the current generation but also in the successive generation, resulting in a sustained infection in the larva population for at least 48 days.","Under diferent concentrations of CnmeGV (7.5x10(11) and 1.125x10(12) occlusion body (OB) ha(-1)) at 30 days after spraying, larval population reduced up to 76.32% and rice leaf rolled rate kept in 15.42%.","Simultaneously, CnmeGV had no impact on arthropod predators of C. medinalis, with abundances ranging from 2.39 to 3.79 per ten hills.","These results revealed that CnmeGV is suitable as a bio-pesticide for rice leaffolder management in rice paddies."])
print(predictions, raw_outputs)

INFO:simpletransformers.classification.classification_utils: Converting to features started. Cache is not used.


  0%|          | 0/7 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

['BACKGROUND', 'BACKGROUND', 'METHODS', 'RESULTS', 'RESULTS', 'RESULTS', 'CONCLUSIONS'] [[ 5.88671875  0.18774414 -2.640625   -1.38574219 -0.86865234]
 [ 5.99609375 -0.10028076 -2.57226562 -1.46679688 -0.81347656]
 [-1.328125   -1.83886719  3.0625      2.4921875  -1.34765625]
 [-1.43066406 -3.83398438 -1.85644531  4.12109375  2.32421875]
 [-2.12304688 -3.55078125 -0.96289062  5.796875    0.21936035]
 [-1.66113281 -3.95507812 -2.05078125  5.08984375  2.10742188]
 [-1.64355469 -2.16015625 -2.24023438 -0.20043945  5.859375  ]]


In [ ]:
!nvidia-smi

Sat Apr 10 08:56:03 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.67       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   77C    P0    47W /  70W |   3822MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------